version: "3"
services:
  db:
    container_name: paper_db
    image: postgres:10.4-alpine
    env_file:
      - env_file
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    container_name: paper_cache
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: paper_web
    env_file:
      - env_file
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
      - redis
volumes:
  dbdata:
